## Matrices

In [2]:
import numpy as np

In [3]:
a = np.matrix([[1,4,7],[2,5,8],[3,6,9]])
a

matrix([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])

In [4]:
b = np.matrix([[1,-1,2],[2,-1,2],[3,-3,0]])
b

matrix([[ 1, -1,  2],
        [ 2, -1,  2],
        [ 3, -3,  0]])

In [11]:
mult = a@b
suma = a+b

mult 
suma

matrix([[ 2,  3,  9],
        [ 4,  4, 10],
        [ 6,  3,  9]])